# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      npm install -g scriptless-cli
      scriptless-cli run --cloudURL "https://demo.app.perfectomobile.com" --securityToken "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4YmI4YmZmZS1kMzBjLTQ2MjctYmMxMS0zNTYyMmY1ZDkyMGYifQ.eyJpYXQiOjE2NTg5Mzg0ODQsImp0aSI6IjUzNDVmNTUyLTQ5M2YtNGQyMC1iZjE2LTZlZmJlMzYzMjI3YSIsImlzcyI6Imh0dHBzOi8vYXV0aC5wZXJmZWN0b21vYmlsZS5jb20vYXV0aC9yZWFsbXMvZGVtby1wZXJmZWN0b21vYmlsZS1jb20iLCJhdWQiOiJodHRwczovL2F1dGgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2RlbW8tcGVyZmVjdG9tb2JpbGUtY29tIiwic3ViIjoiNjdlMmFiOWYtOWRkMC00YTcyLTg2ZmItMWRhMjU3OTJjYzgzIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Im9mZmxpbmUtdG9rZW4tZ2VuZXJhdG9yIiwibm9uY2UiOiI5NTFjMzJkZC1mNmI2LTRhZTYtYmY1ZS01NTFlZmRhZjU2MzMiLCJzZXNzaW9uX3N0YXRlIjoiNTIzMTcwMzUtNmZhNy00MDNiLThiYzgtM2YzYTBjMTI5OWIzIiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MifQ.abw5siv3957jO55KcNHFx7psGRJXsS0OjpwERcRBkNQ" -p "demo" -v "Base" -j "Job1" -l "Chrome 1024x768" -e "https://www.bankofamerica.com(Default)"